Repository AGH-Narzedzia-Informatyczne-2022-2023/postaw-na-milion, pull requests merged in 2022-11, with the labels that each got.

#12 Add end screen
  src/end_page.py
  src/ui.py
Labels: help wanted

#13 add question page
  src/question_page.py
Labels: question

#14 Question handler
  src/api_question_getter.py
  src/game.py
  src/question_handler.py
  src/question_page.py
  src/ui.py
Labels: help wanted

#15 Accept only correct answer
  src/end_page.py
  src/question_page.py
  src/ui.py
Labels: enhancement
